version: '3'

#Networks
networks:
  default:
    name: facebook

#Volumes
volumes:
  dbdata:
    driver: local

services:
    #MYSQL Service
    db:
        container_name: facebook_mysql
        image: mariadb:10.5.15
        command:
            --sql_mode="IGNORE_SPACE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "3306:3306"
        logging:
            driver: "json-file"
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        env_file:
            - .env
        networks:
            - default
    #Laravel app
    app:
        container_name: facebook_app
        image: php:8.1-fpm
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        depends_on:
            - db
        volumes:
            - ./:/project
        ports:
            # - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
            - '8000:8000'
            - '3000:3000'
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: facebook_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: facebook_mysql
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        ports:
            - "8080:80"
        networks:
            - default

    redis:
        image: redis
        container_name: facebook_redis
        restart: unless-stopped
        networks:
            - default
