#!/bin/bash

VENDOR_DIR="$PWD/vendor"
NODE_MODULES_DIR="$PWD/node_modules"
CUSTOM_COMMAND=""
CONTAINER_NAME="facebook_app"
COMPOSER_IMAGE="composer:2"
NODE_IMAGE="node:18-alpine"
PHP_IMAGE="php:8.1"

app(){

    COMMAND=$1

    if [ -z "$COMMAND" ]
    then
        print_help
        return 0;
    fi

    install_dependecies

    case $COMMAND in
        setup)
            setup
            ;;
        start)
            start_server
            ;;
        npm)
            npm
            ;;
        php)
            php
            ;;
        composer)
            composer
            ;;
        exec)
            execute
            ;;
        stop)
            kill_container
            ;;
        help)
            print_help
            ;;
        *)
        echo "No such command: $COMMAND"
        echo ""
        print_commands
        ;;
    esac
}

print_help(){
    echo "Commands:"
    echo "  setup       Setup enviroment"
    echo "  start       Serve laravel and react app"
    echo "  npm         Run npm command"
    echo "  php         Run php command"
    echo "  composer    Run composer command"
    echo "  exec        Run custom command on container"
    echo "  stop        Stop running container"
    echo "  help        Show usage help"
    echo ""
}

setup(){
    if [ ! -f ".env" ]
    then
        cp .env.example .env
    fi

    CUSTOM_COMMAND="artisan key:generate"
    php

    build_image

    start_server
}

start_server(){
    CUSTOM_COMMAND="npm run dev"

    execute

    echo "Server listening on http://localhost:8000"
}

npm(){
    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $NODE_IMAGE npm $CUSTOM_COMMAND
}

php(){
    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $PHP_IMAGE php $CUSTOM_COMMAND
}

composer(){
    echo "uso u composer"
    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $COMPOSER_IMAGE -o --ignore-platform-reqs --no-plugins $CUSTOM_COMMAND
}

kill_container(){
    docker-compose down
}

execute(){
    CONTAINER_EXISTS=$(docker container ls | grep "facebook_app")

    if [ -z "$CONTAINER_EXISTS" ]
    then
        docker-compose up -d
    fi

    docker exec -d -w /project $CONTAINER_NAME $CUSTOM_COMMAND
}

install_dependecies(){

    if [ ! -d "$VENDOR_DIR" ] || [ ! -d "$NODE_MODULES_DIR" ]
    then
        CUSTOM_COMMAND="install"

        npm
        composer
    fi
}

build_image(){
    docker-compose build
}

if [ -z "$2" ]
then
    echo $1
    app $1
else
    CUSTOM_COMMAND=${@: 2}
    app $1
fi
