#!/bin/bash

VENDOR_DIR="$PWD/vendor"
NODE_MODULES_DIR="$PWD/node_modules"
CUSTOM_COMMAND=""
CONTAINER_NAME="facebook_app"
COMPOSER_IMAGE="composer:2"
NODE_IMAGE="node:18-alpine"
PHP_IMAGE="php:8.1"

app(){

    COMMAND=$1

    if [ -z "$COMMAND" ]
    then
        print_help
        return 0;
    fi

    if [ ! -d "$VENDOR_DIR" ] || [ ! -d "$NODE_MODULES_DIR" ]
    then

        if [ $1 != "setup" ]
        then
            setup
        fi

    fi

    case $COMMAND in
        setup)
            setup
            ;;
        start)
            start_server
            ;;
        exec)
            execute
            ;;
        kill)
            execute
            ;;
        help)
            print_help
            ;;
        *)
        echo "No such command: $COMMAND"
        echo ""
        print_commands
        ;;
    esac
}

print_help(){
    echo "Commands:"
    echo "  setup     Setup enviroment"
    echo "  start     Serve laravel and react app"
    echo "  exec      Run custom command on container"
    echo "  help      Show usage help"
    echo ""
}

setup(){

    if [ ! -f ".env" ]
    then
        cp .env.example .env
    fi

    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $COMPOSER_IMAGE -o --ignore-platform-reqs --no-plugins install

    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $NODE_IMAGE npm install

    docker run \
        --rm --interactive --tty \
        --volume ${PWD}:/app \
        --workdir /app \
        $PHP_IMAGE php artisan key:generate

    start_server

    echo "Server listening on http://localhost:8000"
}

start_server(){
    CUSTOM_COMMAND="npm run dev"
    execute
}

kill_container(){
    docker-compose down
}

execute(){
    CONTAINER_EXISTS=$(docker container ls | grep "facebook_app")

    if [ -z "$CONTAINER_EXISTS" ]
    then
        docker-compose up -d
    fi

    docker exec -d -w /project/facebook-clone $CONTAINER_NAME $CUSTOM_COMMAND
}

if [ -z "$2" ]
then
    echo $1
    app $1
else
    CUSTOM_COMMAND=${@: 2}
    app $1
fi
